theme: "hugo-PaperMod"
baseURL: /
languageCode: ru-Ru
title: 🅸🅽🆅🅴🆂🆃🅲🅾🅾🅺🅸🅴🆂

params:
    homeInfoParams:
        Title: 🍪 🍪 🪙
        Content: Блог про инвестиции, финансы, экономику, data scienсe, визуализацию -- **Больше количественного и качественного анализа** 😎  <br><br> Hi there 👋 this is blog about data science, financial markets and economics
    socialIcons: # optional
        - name: "email"
          url: "mailto:d.kibalnikov@gmail.com"
        - name: "github"
          url: "https://github.com/dkibalnikov"
        - name: "telegram"
          url: "https://t.me/investcookies"
        - name: "rss"
          url: "index.xml"
        - name: "linkedin"
          url: "https://www.linkedin.com/in/dmitry-kibalnikov-7134aa2a/"
        - name: "facebook"
          url: "https://www.facebook.com/Kibalnikov.Dmitry"
    ShowReadingTime: true
    ShowBreadCrumbs: true
    ShowPostNavLinks: true
    comments: true
    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     findAllMatches: true
    #     ignoreLocation: true
    #     location: 0
    #     distance: 100
    #     threshold: 0.4
    #     minMatchCharLength: 1
    #     keys: ["content", "title", "permalink", "summary"]
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    ShowShareButtons: true

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
    main:
        - identifier: categories
          name: categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: tags
          url: /tags/
          weight: 20
        - identifier: search
          name: search 
          url: /search/
          weight: 30
        - identifier: about
          name: about
          url: /about/
          weight: 30
          
disqusShortname: dmitrykibalnikov
          
markup:
  goldmark:
    renderer:
      unsafe: true

googleAnalytics: G-STNC3D15LX

# languages:
#     ru:
#         languageName: ":ru:"
#         weight: 10
#         title: InvestCookies
#         menu:
#             main:
#                 - name: Поиск
#                   url: search/
#                   weight: 10
#                 - name: Теги
#                   url: tags/
#                   weight: 10
#                 - name: Категории
#                   url: categories/
#                   weight: 10
#     en:
#         languageName: "En"
#         params:
#           homeInfoParams:
#             Title: 🍪 🍪 🪙
#             Content: Hi there 👋  this is blog about datascience, financial markets and economics
#         weight: 1
#         menu:
#             main:
#                 - name: Search
#                   url: search/
#                   weight: 10
#                 - name: Tags
#                   url: tags/
#                   weight: 10
#                 - name: Categories
#                   url: categories/
#                   weight: 10