theme: "hugo-PaperMod"
baseURL: /
languageCode: ru-Ru
title: InvestCookies 

params:
    homeInfoParams:
        Title: 🍪 🍪 🪙
        Content: Это блог про инвестиции, финансы, экономику, datascienсe, визуализацию, - вне политики и без скрытых бенифициаров
    ShowShareButtons: true
    socialIcons: # optional
        - name: "email"
          url: "mailto:d.kibalnikov@gmail.com"
        - name: "github"
          url: "https://github.com/dkibalnikov"
        - name: "telegram"
          url: "https://t.me/Kb_Dm"
        - name: "rss"
          url: "index.xml"
        - name: "linkedin"
          url: "https://www.linkedin.com/in/dmitry-kibalnikov-7134aa2a/"
        - name: "facebook"
          url: "facebook.com"
    ShowReadingTime: true
    ShowBreadCrumbs: true
    comments: true
    
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
    main:
        - identifier: categories
          name: categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: tags
          url: /tags/
          weight: 20
        - identifier: search
          name: search
          url: /search/
          weight: 30
          
disqusShortname: dmitrykibalnikov
          
markup:
  goldmark:
    renderer:
      unsafe: true
