---
title: "Разбор отчтености VK"
author: "🍪🍪🪙"
date: 2022-08-16
categories: ["экономика"]
tags: ["для всех", "анализ", "stock market", "для новичков", "бизнес"]
math: false
ShowToc: true
cover:
    image: "vladimir_kirienko"
    alt: "<Vladimir Kirienko>"
    caption: "<text>"
    relative: true # To use relative path for cover image, used in hugo Page-bundles
---

<script src="{{< blogdown/postref >}}index_files/htmlwidgets/htmlwidgets.js"></script>
<script src="{{< blogdown/postref >}}index_files/d3/d3.min.js"></script>
<script src="{{< blogdown/postref >}}index_files/dagre/dagre-d3.min.js"></script>
<link href="{{< blogdown/postref >}}index_files/mermaid/dist/mermaid.css" rel="stylesheet" />
<script src="{{< blogdown/postref >}}index_files/mermaid/dist/mermaid.slim.min.js"></script>
<link href="{{< blogdown/postref >}}index_files/DiagrammeR-styles/styles.css" rel="stylesheet" />
<script src="{{< blogdown/postref >}}index_files/chromatography/chromatography.js"></script>
<script src="{{< blogdown/postref >}}index_files/DiagrammeR-binding/DiagrammeR.js"></script>

## Вступление

*Моя жизнь прошла в атмосфере нефти и газа.*

<div>

*--- Виктор Черномырдин*

</div>

Знакомьтесь, на тизере статьи фото Владимира Кириенко – сына того самого Сергея Кириенко, который в настоящий момент возглавляет администрацию президента РФ. Население постарше помнит Сергея Кириенко, который провел страну через дефолт 1998 года, а злой на язык народ закрепил за ним прозвище “Киндрер Сюрприз” потому что появления новой персоны на месте настоящего мастодонта политики того времени - Виктора Черномырдина - было весьма неожиданным. Долгое время Сергей Кириенко весьма успешно возглавлял Росатом, а теперь его сын возглавляет одного из крупнейших игроков ИТ-рынка страны. На самом деле, у меня нет никакого желания провоцировать у читателя негативные коннотации к назначению Владимира Кириенко на пост главы VK, но я лишь хочу показать какие традиции и какая, можно сказать, управленческая династия стоит за новым лицом в мире ИТ. Думаю, этот абзац следует закончить одной из бессмертных фраз Виктора Черномырдина: “Много говорить не буду, а то опять чего-нибудь скажу…”🙊

Отчетность компаний – это совершенно потрясающий источник информации, в котором многие детали говорят больше чем цифры в графе `Доход на акцию`. Посмотрите внимательно на фотографию протагониста этой заметки, взятую с отчета VK - черная водолазка – это наверное самый избитый символ в мире ИТ, который вызывает стойкие ассоциации со Стивом Джобсом даже у далеких от ИТ людей. Ироничная улыбка информирует вас, что новый глава VK знает правила игры и понимает, что ему нужно надеть черную водолазку, а не официальный костюм. Обратите внимание как креативно был выбран цвет: водолазка не совсем черная, а слегка серая. Что тут можно сказать? Очень смелый и креативный шаг. Впрочем, я бы предпочел увидеть главу VK в футболке VK, что могло давать намек на некую самобытность 🪆

В данной заметке я бы хотел кратко, но системно изложить принципы формирования отчетных балансов и их взаимосвязь, а также почитать отчет VK и сделать выводы, которые должен делать инвестор т.е. принять решение: продавать или покупать. Думаю, такая заметка выглядит весьма интересной на фоне *\~30%* роста в канун выхода не аудированной отчетности за 2 квартал 2022 года[^1]. Впрочем судя по котировкам VK последних дней отчет скорее разочаровал инвесторов. Кроме того, следует напомнить, что акции VK сейчас торгуются по цене в **5-6 раза** дешевле цены размещения.

<img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-2-1.png" width="672" />

## Про отчетность

<div>

*Надо же думать, что понимать.*

*--- Виктор Черномырдин*

</div>

Сразу хочу отдать должное менеджменту VK: на фоне появившейся моды скрывать/засекречивать отчетность VK скорее действует наоборот – отёчность очень подробная и дает возможность анализировать структуру выручки и расходов. Сам этот факт можно занести в жирные плюсы при рассмотрении этой бумаги для инвестиций 👍

В любом более-менее приличном отчете организации вы найдете как минимум три раздела:

-   Баланс Доходов Расходов (Profit and Losess)

-   Движении Денежных Средств (Cash Flow)

-   Баланс Активов и Обязательств (StatementBalance Sheet)

<div id="htmlwidget-1" style="width:672px;height:480px;" class="DiagrammeR html-widget"></div>
<script type="application/json" data-for="htmlwidget-1">{"x":{"diagram":"graph TD\n   A(<b>Баланс<\/b><br> доходов и<br> расходов) ==>|Переоценка|C(<b>Баланс<\/b> <br> активов и<br> обязательств)\n   B(<b>Баланс<\/b> <br> поступлений <br> и платежей)==>|Оплаты|C\n\n   style A fill:#4E79A7, stroke:#333, opacity:0.7\n   style B fill:#F28E2B, stroke:#333, opacity:0.7\n   style C fill:#E15759, stroke:#333, opacity:0.7\n"},"evals":[],"jsHooks":[]}</script>

Возникает вопрос – почему три отчета и почему нельзя ограничится только отчетом Доходов Расходов? Потому как там есть главное, что интересует инвестора – прибыль, которую он получит будучи акционером. В действительности, система отчетности должна отвечать не только на вопрос сколько компания заработала, но также давать ответы на массу других вопросов, которые могут волновать инвестора:

-   Существует ли риск кассового разрыва и неуплаты платежей поставщикам или дефолта по обязательствам ?
-   Из чего формируется валовая прибыль и существует ли потенциал дальнейшего роста ?
-   Имеются ли скрытые резервы для роста чистой прибыли ?

Различные виды отчетов позволяют взглянуть под разными углами на деятельность компании, но одновременно с этим обеспечивает целостность сведений т.к. статьи одного отчета взаимосвязаны со статьями другого отчета, что существенно осложняет пространство для преднамеренных или неумышленных искажений реальной ситуации.

## Про долги

*Отродясь такого не бывало, и вот опять то же самое*

<div>

*--- Виктор Черномырдин*

</div>

Инвестор может иметь вложения в бумаги фиксированного займа эмитента т.е. в данном случае рассматривается пример покупки облигаций VK. Такого инвестора не интересует прибыль т.к. платежи по купону являются фиксированными обязательствами и не зависят от прибыли, но интересует финансовая устойчивость компании. Самое простое, что можно сделать для оценки финансовой устойчивости – это посмотреть в отчете Баланс Активов и Обязательств. Действительно, получить кассовый разрыв гораздо проще когда у тебя на счету считанные копейки, а краткосрочные платежи поставщикам и кредиторам очень даже ощутимы. Существуют более продвинутые методики оценки финансовой устойчивости через собственный капитал, но я бы оставил их на обсуждение всероссийскому съезду бухгалтеров т.к. речь идет о совокупности слабо-увязанных удельных показателей. Итак для VK оборотные (краткосрочные, ликвидные) активы:

| **Mлн руб.**                                  | **На 30 июня 2022г.**                                                                  | **На 31 декабря 2021г.** |
|-----------------------------------------------|----------------------------------------------------------------------------------------|--------------------------|
| Торговая дебиторская задолженность            | <a style='color:white; background:#E15759; border-radius:3px;padding: 2px' >14 707</a> | 20 688                   |
| Предоплата по налогу на прибыль               | 300                                                                                    | 359                      |
| Расходы будущих периодов и авансы поставщикам | 3 400                                                                                  | 2 353                    |
| Конвертируемые займы                          | 114                                                                                    | \-                       |
| Займы выданные                                | 200                                                                                    | 109                      |
| Запасы                                        | 515                                                                                    | 157                      |
| Прочие оборотные активы                       | 1 306                                                                                  | 1 445                    |
| Денежные средства и их эквиваленты            | <a style='color:white; background:#E15759; border-radius:3px;padding: 2px' >12 385</a> | 23 737                   |
| **Итого оборотные активы**                    | **32 927**                                                                             | **48 848**               |

Я <a style='color:white; background:#E15759; border-radius:3px;padding: 2px' >выделил</a> две цифры которые способствовали существенному снижению оборотного капитала. Напомню, что `дебиторская задолженность` – это обязательство контрагентов оплатить оказанные им услуги в адрес VK.

Далее краткосрочные обязательства:

| **Mлн руб.**                                             | **На 30 июня 2022г.**                                                                  | **На 31 декабря 2021г.** |
|----------------------------------------------------------|----------------------------------------------------------------------------------------|--------------------------|
| Торговая кредиторская задолженность                      | 13 145                                                                                 | 14 541                   |
| Обязательства по налогу на прибыль                       | 2 804                                                                                  | 3 208                    |
| НДС и прочие налоговые обязательства                     | 4 399                                                                                  | 4 391                    |
| Отложенная выручка и авансы полученные от клиентов       | 16 874                                                                                 | 17 980                   |
| Краткосрочные процентные кредиты и облигации             | <a style='color:white; background:#E15759; border-radius:3px;padding: 2px' >37 161</a> | 7 078                    |
| Краткосрочные обязательства по аренде                    | 5 163                                                                                  | 4 121                    |
| Краткосрочные финансовые обязательства, оцениваемые      |                                                                                        |                          |
| по справедливой стоимости через прибыль или убыток       | 4 751                                                                                  | \-                       |
| Прочие краткосрочные обязательства и начисленные расходы | 10 263                                                                                 | 10 123                   |
| **Итого краткосрочные обязательства**                    | **94 560**                                                                             | **61 442**               |

В итоге получается, что на первое полугодие 2022 имеется баланс по краткосрочным активам/обязательствам **минус \~62 млрд. рублей** тогда как на второе полугодие 2021 было **минус \~13 млрд. рублей**. Тенденция не очень позитивная, особенно, если принимать внимание, что капитал VK составляет **\~120 млрд. рублей** ⚖️

Если посмотреть на деятельность VK несколько под иным углом, а конкретно в части движения денежных средств, то можно использовать достаточно популярную метрику оценки платежеспособности и также способности направлять денежные ресурсы на стратегические инициативы – Free Cash Flow (FCF, Свободный денежный поток). Данные показатель получается простым вычитанием капитальных затрат из операционного денежного потока. За первое полугодие 2021 года FCF составил **3,11 млрд. рублей** тогда как за аналогичный период 2022 эта метрика опустилась до **минус 2,43 млрд. рублей**, что говорит о возможных существенных затруднениях при реализации стратегических программ и обслуживании долга.

Тем не менее, VK в текущий момент имеет доступ практически к безграничным финансовым ресурса и всерьез ожидать кассовые разрывы – не приходится. Если кто-то не в курсе то VK с недавних пор принадлежит Газпрому – тому самому, который недавно некрасиво обошелся с миноритариями, не выплатив дивиденды. Саму связь Газпрома и VK вряд ли можно назвать простой, пожалуй, процитирую [Википедию](https://ru.wikipedia.org/wiki/VK_(%D0%BA%D0%BE%D0%BC%D0%BF%D0%B0%D0%BD%D0%B8%D1%8F)#%D0%A1%D0%BE%D0%B1%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%B8%D0%BA%D0%B8_%D0%B8_%D1%80%D1%83%D0%BA%D0%BE%D0%B2%D0%BE%D0%B4%D1%81%D1%82%D0%B2%D0%BE) в этой части:

> В России компания зарегистрирована как ООО «ВК», которая через ООО «Компания ВК» на 99,99 % принадлежит «MGL Mail.ru Equity Limited» (Лимасол, Кипр), которая в свою очередь, принадлежит компании «Mail Coöperatief U.A.» (Амстердам, Нидерланды). Последняя принадлежит компании «VK Company Limited» (зарегистрирована на Британских Виргинских островах, главный офис находится в Лимасоле). Конечным контролирующим акционером является Газпром, в свою очередь контролируемый правительством РФ.

Напомню, что про офшоры я публиковал достаточно подробную заметку [Офшорный рубль 🏝🏝🏝](/post/offshore_economics/) и тут же следует заметить, что потеря налогового резиденства в Нидерландах карается выплатой дополнительного налога, что автоматически отразиться на отчетности при репатриации актива в юрисдикцию РФ. Напомню, что РФ разорвала соглашение о двойном налогообложении и юрисдикция в Нидерландах превратилась в налоговую обузу.

## Про EBIDTA

*Мы до сих пор пытаемся доить тех, кто и так лежит.*

<div>

*--- Виктор Черномырдин*

</div>

Прибыль – это всегда важно, но прибыль может формироваться на базе основной деятельности, но также с учетом факторов, которые находятся вне контроля менеджмента компаний, например:

-   Выплата процентов по кредитам может сильно зависеть от денежно-кредитной политики конкретного временного периода
-   Размер амортизации основных средств сильно зависит от того, какую стратегию амортизации выбрала бухгалтерия
-   Налоговые ставки могут также меняться, например, сейчас ИТ компании получили серьезные преференции в отношении налога на прибыль[^2]

В моей практике разговор с топ-менеджерами компаний о показателях эффективности очень часто сводился к EBIDTA – Earnings Before Interest, Taxes, Depreciation т.е. прибыль до платежей по кредитам, налогов и амортизации. Этот показатель весьма условно, но отделяет эффективность работы менеджмента от внешних факторов. В отношении выручки EBIDTA VK формируется следующим образом:

| **млн руб.**                   | **2 кв. 2021** | **2 кв. 2022** | **г./г., %**                                                                          |
|--------------------------------|----------------|----------------|---------------------------------------------------------------------------------------|
| **Выручка**                    |                |                |                                                                                       |
| Онлайн реклама                 | 11 250         | 14 344         | <a style='color:white; background:#E15759; border-radius:3px;padding: 2px' >27,5%</a> |
| ММО игры                       | 9 362          | 9 220          | -1,5%                                                                                 |
| Пользовательские платежи       | 4 532          | 4 192          | -7,5%                                                                                 |
| Образовательные технологии     | 2 011          | 2 578          | 28,2%                                                                                 |
| Прочая выручка                 | 2 533          | 2 502          | -1,2%                                                                                 |
| **Итого выручка**              | **29 688**     | **32 836**     | <a style='color:white; background:#E15759; border-radius:3px;padding: 2px' >10,6%</a> |
| *Корректировки*                |                |                |                                                                                       |
| Бартерная выручка              | \-             | \-             | n/a                                                                                   |
| Изменения в отложенной выручке | 303            | (1 676)        | n/m                                                                                   |
| **Скорректированная выручка**  | **29 991**     | **31 160**     | **3,9%**                                                                              |

Во втором квартале 2022 весьма уверенно выросла выручка от `онлайн рекламы` **27.5%**, что связано, весьма вероятно, с уходом прямых и косвенных конкурентов с рынка РФ. Думаю, эффект себя еще не исчерпал, но больших приростов по этому направлению ждать не приходится. Аудитория Facebook в РФ была все-таки не столь значительна, а Instagram скорее косвенный, но не прямой конкурент. Вот картинка с сайта Forbes, чтобы не быть голословным:

<embed type="text/html" src="https://e.infogram.com/aaec5c26-43cf-4c87-95ba-1bd51433539e?parent_url=https%3A%2F%2Fwww.forbes.ru%2Ftekhnologii%2F473713-kak-inostrannye-socseti-teraut-popularnost-v-rossii-posle-specoperacii&src=embed#igc-cp-curtain-chart-2" width="750" height="650">

Если картинка не появилась – значит Forbes куда-то ее перенес или она не доступна на территории вашего прибывания

Отчетливо видно как VK пожрал аудиторию Facebook прибавив 5 млн. пользователей тогда как 30 млн. аудитории Instagram просто пропала с радаров и большим вопросом остается: сможет ли VK на себя перетянуть этот трафик. Подытоживая я бы не стал ждать резкого роста аудитории VK в ближайшие годы без расширения географии присутствия.

Далее сегмент `ММО игры` стагнировал и показал символическое сокращение, но сегмент весьма перспективный и вероятно наверстает темпы инфляции к следующему полугодию.

Прочие менее значимые сегменты в совокупности стагнировали, а общий итог составил **10,6%** роста выручки, что опять таки не поспевает за уровнем инфляции **\~15%**.

В части затрат следует отметить существенный рост расходов на персонал **34,6%**, что может быть хорошо, если деньги пошли на программистов [^3] или плохо, если деньги пошли на зарплаты новой команды топ-менеджеров. Согласно пресс-релизу VK планировалось нанять 1000 человек тогда как расходы на персонал увеличились на **2 842 млн. руб.**. Примем во внимание индексацию ФОТ в размере **15%** для работающего персонала и получим, что на условно новых 1000 сотрудников было потрачено **1 897 млн. руб.** или приблизительно **630 тыс. руб.** на человека, что выглядит завышено с учетом льгот для ИТ компаний на страховые взносы в размере **7,6%** против **30%** для прочих секторов экономики. Я могу согласиться, что за хорошего тех. лида можно заплатить пол миллиона, но VK явно не нанимал 1000 исключительно лидов и супер экспертов. Также нужно понимать, что рынок ИТ специалистов сейчас находится не в лучшей форме и многие мои знакомые из ИТ были морально готовы даже на понижение их доходов. Напомню, что ранее я писал о проблемах рынка ИТ в кризис [Кому на Руси жить хорошо? 🤔](/post/money_flows1/)

Чуть менее, но тоже ощутимо увеличились расходы на маркетинг **22,3%**, что отчасти закономерно для роста выручки по основному виду деятельности.

| **млн руб.**                                       | **2 кв. 2021** | **2 кв. 2022** | **г./г., %**                                                                           |
|----------------------------------------------------|----------------|----------------|----------------------------------------------------------------------------------------|
| **Операционные расходы**                           |                |                |                                                                                        |
| Расходы на персонал                                | (8 209)        | (11 051)       | <a style='color:white; background:#E15759; border-radius:3px;padding: 2px' >34,6%</a>  |
| Вознаграждение агентам/партнерам                   | (8 628)        | (8 000)        | -7,3%                                                                                  |
| Маркетинговые расходы                              | (5 375)        | (6 574)        | <a style='color:white; background:#E15759; border-radius:3px;padding: 2px' >22,3%</a>  |
| Расходы на хостинг серверов                        | \(207\)        | \(222\)        | 7,2%                                                                                   |
| Профессиональные услуги                            | \(386\)        | \(337\)        | -12,7%                                                                                 |
| Прочие операционные доходы                         | 153            | 233            | 52,3%                                                                                  |
| Прочие операционные расходы                        | (1 587)        | (1 313)        | -17,3%                                                                                 |
| **Итого операционные расходы, нетто**              | **(24 239)**   | **(27 264)**   | **12,5%**                                                                              |
| *Корректировки*                                    |                |                |                                                                                        |
| Платежи, основанные на акциях                      | 432            | 251            | -41,9%                                                                                 |
| Прочее                                             | 478            | 59             | -87,7%                                                                                 |
| **Скорректированный показатель EBITDA**[^4]        | **6 662**      | **4 206**      | <a style='color:white; background:#E15759; border-radius:3px;padding: 2px' >-36,9%</a> |
| *рентабельность скорр. EBITDA*                     | ***22,2%***    | ***13,5%***    |                                                                                        |
|                                                    |                |                |                                                                                        |
| **Чистая прибыль/(убыток)**                        | **(4 977)**    | **3 616**      | **n/m**                                                                                |
| *Рентабельность чистой прибыли/(убытка)*           | ***-16,8%***   | ***11,0%***    |                                                                                        |
|                                                    |                |                |                                                                                        |
| **Скорректированный чистый убыток**                | **(2 232)**    | **(3 435)**    | **53,9%**                                                                              |
| *Рентабельность скорректированного чистого убытка* | ***-7,4%***    | ***-11,0%***   |                                                                                        |

Результатом всей деятельности за период стало сокращение EBITDA на ощутимые **-36,9%**, что является весьма тревожным фактом для акционеров 🚨

## Про прибыль

*Надо делать то, что нужно нашим людям, а не то, чем мы здесь занимаемся.*

<div>

*--- Виктор Черномырдин*

</div>

Если поговорить с финансовыми директорами или бухгалтерами то можно столкнуться с расхожим мнением о том, что прибыль – это есть во многом компромиссная сумма между менеджментом и акционерами, которую они договорились перевести в свободный капитал для выплаты дивидендов или инвестиций. В данном случае нужно оговориться, что вывод такой прибыли будет не обязательно прозрачным и вполне возможно, что деньги будут утекать в офшоры, ущемляя интересы миноритариев, но я не намерен сейчас погружаться в эту область. Вместо этого, предлагаю посмотреть структуру расходов, которые идут сверх EBIDTA. В данном разделе можно попробовать найти аномальные статьи расходов, которыми “подруливает” менеджмент чтобы показать в отчетности больше или меньше прибыли в зависимости от конъюнктуры:

| **Mлн руб.**                                                                                                                 | **2 кв. 2022**                                                                          | **2 кв. 2021**                                                                          |
|------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------|
| **Скорректированный показатель EBITDA Группы**                                                                               | **4 206**                                                                               | **6 662**                                                                               |
| Изменение отложенной выручки                                                                                                 | 1 676                                                                                   | \(303\)                                                                                 |
| Платежи, основанные на акциях                                                                                                | \(251\)                                                                                 | \(432\)                                                                                 |
| Резерв под ожидаемые кредитные убытки по вознаграждению к получению                                                          | \-                                                                                      | \(473\)                                                                                 |
| Прочее                                                                                                                       | \(59\)                                                                                  | \(5\)                                                                                   |
| Износ и амортизация                                                                                                          | <a style='color:white; background:#E15759; border-radius:3px;padding: 2px' >(4 815)</a> | <a style='color:white; background:#E15759; border-radius:3px;padding: 2px' >(4 413)</a> |
| Доля в убытке ассоциированных организаций и совместных предприятий, учитываемых по методу долевого участия                   | (3 906)                                                                                 | (5 441)                                                                                 |
| Финансовые доходы                                                                                                            | 341                                                                                     | 246                                                                                     |
| Финансовые расходы                                                                                                           | (1 552)                                                                                 | \(955\)                                                                                 |
| Прочие внереализационные доходы/(расходы)                                                                                    | 141                                                                                     | \(61\)                                                                                  |
| Чистый (убыток)/прибыль от финансовых активов и обязательств, оцениваемых по справедливой стоимости через прибыль или убыток | (3 676)                                                                                 | 26                                                                                      |
| Убыток от переоценки финансовых инструментов                                                                                 | \(1\)                                                                                   | \(124\)                                                                                 |
| Резерв под ожидаемые кредитные убытки по денежным средствам с ограниченным правом использования                              | 358                                                                                     | \-                                                                                      |
| Чистая прибыль от курсовых разниц                                                                                            | 14 436                                                                                  | 812                                                                                     |
| **Консолидированная прибыль/(убыток) до налогообложения по МСФО**                                                            | **6 898**                                                                               | **(4 461)**                                                                             |

Первое на что следует обратить внимание – это размер амортизации: динамика год к году весьма консервативная, но вот если посчитать темпы амортизации, взяв объем основных средств из отчета `Активов и обязательств`:

| **Mлн руб.**                                                                      | **На 30 июня 2022г.**                                                                  | **На 31 декабря 2021г.**                                                               |
|-----------------------------------------------------------------------------------|----------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------|
| **АКТИВЫ**                                                                        |                                                                                        |                                                                                        |
| **Внеоборотные активы**                                                           |                                                                                        |                                                                                        |
| Инвестиции в ассоциированные организации и совместные предприятия,                |                                                                                        |                                                                                        |
| учитываемые по методу долевого участия                                            | 30 629                                                                                 | 48 921                                                                                 |
| Гудвил                                                                            | 129 344                                                                                | 138 600                                                                                |
| Активы в форме права пользования                                                  | 14 732                                                                                 | 14 843                                                                                 |
| Прочие нематериальные активы                                                      | 14 049                                                                                 | 18 324                                                                                 |
| Основные средства                                                                 | <a style='color:white; background:#E15759; border-radius:3px;padding: 2px' >18 686</a> | <a style='color:white; background:#E15759; border-radius:3px;padding: 2px' >15 798</a> |
| Финансовые активы, оцениваемые по справедливой стоимости через прибыль или убыток | 4 098                                                                                  | 6 903                                                                                  |
| Отложенные налоговые активы                                                       | 4 215                                                                                  | 5 157                                                                                  |
| Долгосрочные займы выданные                                                       | 84                                                                                     | 69                                                                                     |
| Авансовые платежи по договорам аренды офисных помещений                           | 475                                                                                    | 462                                                                                    |
| **Итого внеоборотные активы**                                                     | **216 312**                                                                            | **249 077**                                                                            |

Получится следующая картина:

-   В 2021 году темпы амортизации составляли в годовом выражении **1.12%** или, перевернув дробь, получится оценочный срок службы основных средств **0.895 года**

-   В 2022 году темпы амортизации составляли в годовом выражении **1.03%** или, перевернув дробь, получится оценочный срок службы основных средств **0.97 года**

Другими словами, все основные средства на балансе VK амортизируются менее чем за 1 год и это весьма странно с учетом того, что на балансе должно находится преимущественно серверное оборудование и вероятно здания бытового (офис) или технического (ЦОД) назначений. Здания имеют срок амортизации 10 лет и более. Срок амортизации серверного оборудования официально составляет от 2 до 3 лет. Естественно, после 2-3 лет службы сервер не списывают, а он продолжает свою службу еще 3-4 года. Другими словами, рост основных средств для бизнеса VK будет всегда сопровождаться отложенным потенциалом увеличения прибыли при текущей стратегии амортизации и это составляющая может быть весьма существенной и составлять **2-3 млрд. рублей** при остановке закупок нового оборудования.

В разделе внеоборотных ативов можно также заметить самую загадочную строку во всей отчетности VK – это Гудвил. Гудвил очень мутная штука и она показывает разницу между фактической стоимостью и балансовой стоимость поглощенной компании. Переведу пример простыми словами. Допустим, у вас есть сеть ларьков и вы решили приобрести ларек конкурента. Вы приходите к нему и говорите: “я тут посчитал, ты потратил на строительство своего ларька столько то денег, и ларек амортизировался (устарел) на столько то и его цена теперь составляет – 1 млн. рублей”. Вот ответ на это конкурент заявляет, что у него есть постоянные клиенты и этот ларек удачно расположен в проходимом месте и его оценка по, например, дисконтированному денежному потоку - 2 млн. В данном случае при операции слияния и поглощения с другим ларьком придется заплатить 2 млн. рублей и далее в отчете активов и обязательств положить 1 млн. рублей в основные средства, а еще 1 млн. рублей положить в Гудвил. Все достаточно логично и не вызывает подозрений, но вот когда речь заходит про ИТ, то приходиться иметь дело с феями, единорогами и прочими эльфами, которые будут искренне верить в экспоненциальный рост прибыли чего угодно. Именно так лопнул пузырь дот-комов 2001 года, когда ИТ компании сливались и поглощались, раздувая свои Гудвилы до неприличных размеров пока не выяснилось, что в действительности Гудвил ничто иной как ошибочные модели бизнеса, втюханные людям, которые в этом ничего абсолютно не понимают.

В первом квартале 2022 года обесценение Гудвила принесло около **10 млрд. рублей убытка** и, вероятно, эта статья баланса будет генерировать отрицательные значения еще пару лет т.к. совокупный объем Гудвила на балансе VK – **129 344 млн. руб.**, что составляет одну годовую выручку VK.

## Итоги 🍪

*Хотели как лучше, а получилось, как всегда*

<div>

*--- Виктор Черномырдин*

</div>

По результатам анализа отчетности можно вынести следующее моменты относительно перспектив бизнеса VK:

-   ⚖️ Главой VK назначен представитель управленческой династии с фамилией Кириенко, что с одной стороны говорит о существенном ресурсе, но также означает повышенные риски для акционеров в виде непоследовательной дивидендной политики, обусловленной политическими приоритетами нового менеджмента

-   👍 Отчетность VK отличается высокой детализацией и прозрачностью

-   👎 VK существенно потерял в оперативных ресурсах: и без того отрицательный баланс краткосрочных активов и обязательств увеличился в **4 раза** с **минус \~13 млрд. рублей** до **минус \~62 млрд. рублей**

-   👎 VK принадлежит Газпрому через целую цепочку офшорных юрисдикций, выход из которых может нести дополнительные издержки на фоне отмены с Нидерландами соглашения о двойном налогообложении

-   👍 Выручка по основному сегменту Онлайн рекламы выросла на **27,5%** видимо за счет пожирания аудитории Facebook и частично Instagram, но дальнейший существенный рост выручки в этом сегменте будет ограничен в рамках замкнутого рынка РФ

-   👎 Выручка по прочим сегментам стагнировала и итоговый рост выручки год к году **10,6%**, что не перекрывает оценочный уровень инфляции **15%**

-   ⚖️ Существенно увеличились расходы на персонал **34,6%**, что подразумевает больший уровень инвестиций, но также может подразумевать неуемные амбиции менеджмента в отношении своих зарплатно-бонусных ожиданий

-   👍 Существует некоторый потенциал **2-3 млрд. рублей** роста чистой прибыли в квартал за счет сокращения амортизационных отчислений

-   👎 Гудвил VK составляет одну годовую выручку VK и минимум на пару лет будет приносить отрицательный вклад в прибыль

-   👍 Налоговые послабления для ИТ-компаний **0%** налог с прибыли, страховые взносы **7,6%** вместо **30%** делают данный сектор весьма привлекательным и здесь можно рассчитывать на интенсивный рост в ближайшие годы

Теперь можно принять взвешенное решение относительно привлекательности данной ценной бумаги:

1.  В настоящий момент я не вижу существенных драйверов роста выручки

2.  У меня есть опасения относительно качества корпоративного управления и последовательности дивидендной политики, последнее особо важно при отсутствии существенных драйверов роста

3.  Текущий период на рынке будет сопровождаться громкими заявлениями и сделками по слиянию и поглощению

4.  Планирую продать из своего консервативного портфеля акции VK с некоторым умеренным убытком на какой-нибудь позитивной новости о покупки Авито или части бизнеса Яндекса

5.  В инвестиционном долгосрочном портфеле планирую держать эту бумагу до следующего отчета или продать при чрезмерно позитивной реакции на какую-либо новость

[^1]: [VK Company Limited: неаудированная отчетность за второй квартал 2022 года](https://vk.company/ru/press/releases/11231/)

[^2]: [Льготы для IT- компаний 2022 (подробно)](https://vc.ru/legal/378277-lgoty-dlya-it-kompaniy-2022-podrobno)

[^3]: [В «ВКонтакте» готовы нанять более тысячи айтишников: в России случился дефицит специалистов IT](https://www.vkpress.ru/life/v-vkontakte-gotovy-nanyat-bolee-tysyachi-aytishnikov-v-rossii-sluchilsya-defitsit-spetsialistov-it/?id=144717)

[^4]: См. “Презентация по финансовым данным сегментов Группы” для уточнения реконсиляции показателей, не предусмотренных МСФО (скорректированный показатель выручки, скорректированный показатель EBITDA и скорректированный показатель чистой прибыли/ чистого убытка), в показатели, предусмотренные МСФО.
